{
  "train": {
    "epochs": 80,
    "batch_size": 16,
    "device": "cuda:2",
    "name": "new_arrangement",
    "optim": {
      "name": "adam",
      "lr": 0.0002,
      "lr_decay_steps": 35, 
      "gamma": 0.5
    },
    "model": {
      "model": "distg_unet",
      "dim": 32
    },
    "evaluation": {
      "eval_step": 5
    }
  }
}