{
  "train": {
    "epochs": 80,
    "batch_size": 64,
    "device": "cuda:2",
    "name": "new_arrangement",
    "optim": {
      "name": "adam",
      "lr": 0.0002,
      "lr_decay_steps": 15, 
      "gamma": 0.5
    },
    "model": {
      "model": "distg_unet_reg",
      "dim": 32
    }
  }
}