{
  "train": {
    "epochs": 80,
    "batch_size": 64,
    "device": "cuda:0",
    "name": "run1",
    "optim": {
      "name": "adam",
      "lr": 0.0002,
      "lr_decay_steps": 15, 
      "gamma": 0.5
    },
    "model": {
      "model": "distg",
      "dim": 64
    }
  }
}