{
  "train": {
    "epochs": 80,
    "batch_size": 64,
    "device": "cuda:0",
    "name": "ks=3_new_arrangement",
    "optim": {
      "name": "adam",
      "lr": 0.0001,
      "lr_decay_steps": 35, 
      "gamma": 0.5
    },
    "model": {
      "model": "f3dun",
      "dim": 64
    }
  }
}