{
  "train": {
    "epochs": 50,
    "batch_size": 16,
    "device": "cuda:1",
    "name": "run1",
    "optim": {
      "name": "adam",
      "lr": 0.0001,
      "weight_decay_steps": 35, 
      "gamma": 0.5
    },
    "model": {
      "model": "f3dun",
      "dim": 64
    }
  }
}