{
  "train": {
    "epochs": 80,
    "batch_size": 32,
    "device": "cuda:1",
    "name": "real_data-run1",
    "optim": {
      "name": "adam",
      "lr": 0.00005,
      "lr_decay_steps": 35, 
      "gamma": 0.5
    },
    "model": {
      "model": "ssaformer",
      "dim": 180
    }
  }
}