{
  "train": {
    "epochs": 50,
    "batch_size": 16,
    "device": "cuda:2",
    "name": "run1",
    "optim": {
      "name": "adam",
      "lr": 0.00005,
      "lr_decay_steps": 35, 
      "gamma": 0.5
    },
    "model": {
      "model": "ssaformer",
      "dim": 180
    }
  }
}